export { BrandCharacter } from '@/components/connection/brand/brand-character';
export { BrandCharacterSlot, BrandCharacterScatter } from '@/components/connection/brand/brand-character-slot';
export { BRAND_CHARACTERS_ENABLED } from '@/lib/connection/brand/brand-config';
export { BgTypography } from '@/components/connection/brand/bg-typography';
export { BrandReveal, BrandFloatCard } from '@/components/connection/brand/brand-motion';
export { GlassSurface } from '@/components/connection/brand/glass-surface';
export { BrandScene, BrandTagline, PAGE_CHARACTERS } from '@/components/connection/brand/brand-scene';
export { BrandAuthFrame, BrandAuthLinks } from '@/components/connection/brand/brand-auth-frame';
export { BrandFooter } from '@/components/connection/brand/brand-footer';
export { TiltFrame, ColorBlob, ScatterCharacters, AccentSticker } from '@/components/connection/brand/brand-editorial';
export { HK, BRAND_TAGLINE, BRAND_SUBLINE, SECTION_ACCENTS } from '@/lib/connection/brand/tokens';
export { BRAND_CHARACTERS, CHARACTER_ORDER, type BrandCharacterId } from '@/lib/connection/brand/characters';
